"""empty message

Revision ID: 024dbc455b6b
Revises: 11e37781f331
Create Date: 2025-10-12 17:29:08.255503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '024dbc455b6b'
down_revision = '11e37781f331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('density', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ingredient', schema=None) as batch_op:
        batch_op.drop_column('density')

    # ### end Alembic commands ###
