"""empty message

Revision ID: 03ffea81ea23
Revises: a6a95ac4141a
Create Date: 2026-04-07 22:26:15.763095

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '03ffea81ea23'
down_revision = 'a6a95ac4141a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('cook_temp',
                              existing_type=sa.FLOAT(),
                              type_=sa.Integer(),
                              existing_nullable=True)
        batch_op.alter_column('servings',
                              existing_type=sa.INTEGER(),
                              type_=sa.Float(),
                              existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.alter_column('servings',
                              existing_type=sa.Float(),
                              type_=sa.INTEGER(),
                              existing_nullable=True)
        batch_op.alter_column('cook_temp',
                              existing_type=sa.Integer(),
                              type_=sa.FLOAT(),
                              existing_nullable=True)

    # ### end Alembic commands ###
