"""empty message

Revision ID: 11e37781f331
Revises: e4330a8080ff
Create Date: 2025-10-12 10:54:30.508412

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '11e37781f331'
down_revision = 'e4330a8080ff'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('recipe', schema=None) as batch_op:
		batch_op.alter_column("image", new_column_name="images", type_=sa.Text)


# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('recipe', schema=None) as batch_op:
		batch_op.alter_column("images", new_column_name="images", type_=sa.String(36))

# ### end Alembic commands ###
