"""empty message

Revision ID: 231dc6c3f09c
Revises: 2635a1d858b8
Create Date: 2025-10-05 19:30:08.841624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '231dc6c3f09c'
down_revision = '2635a1d858b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sidebar', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ingredients', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('ingredients')
        batch_op.drop_column('sidebar')

    # ### end Alembic commands ###
