"""initial migration

Revision ID: 850981e700c2
Revises: 
Create Date: 2026-02-16 17:29:48.941908

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '850981e700c2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredient',
                    sa.Column('slug', sa.String(length=50), nullable=False),
                    sa.Column('name', sa.String(length=50), nullable=False),
                    sa.Column('density', sa.Float(), nullable=True),
                    sa.PrimaryKeyConstraint('slug')
                    )
    op.create_table('recipe',
                    sa.Column('slug', sa.String(length=100), nullable=False),
                    sa.Column('name', sa.String(length=100), nullable=False),
                    sa.Column('directions', sa.Text(), nullable=True),
                    sa.Column('images', sa.Text(), nullable=True),
                    sa.Column('sidebar', sa.Text(), nullable=True),
                    sa.Column('ingredients', sa.Text(), nullable=True),
                    sa.PrimaryKeyConstraint('slug')
                    )
    op.create_table('recipe_ingredient_schema',
                    sa.Column('ingredient_list', sa.String(length=100), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('unit', sa.String(length=20), nullable=True),
                    sa.Column('recipe_slug', sa.String(length=100), nullable=False),
                    sa.Column('ingredient_slug', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_slug'], ['ingredient.slug'], ),
                    sa.ForeignKeyConstraint(['recipe_slug'], ['recipe.slug'], ),
                    sa.PrimaryKeyConstraint('ingredient_list', 'recipe_slug', 'ingredient_slug')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_ingredient_schema')
    op.drop_table('recipe')
    op.drop_table('ingredient')
    # ### end Alembic commands ###
