"""added number and image stuff

Revision ID: 9ffa7f847894
Revises: 231dc6c3f09c
Create Date: 2025-10-10 21:27:44.477523

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '9ffa7f847894'
down_revision = '231dc6c3f09c'
branch_labels = None
depends_on = None


def upgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('recipe', schema=None) as batch_op:
		# batch_op.add_column(sa.Column('number', sa.Integer(), nullable=False))
		batch_op.add_column(sa.Column('image', sa.String(length=36), nullable=True))


# ### end Alembic commands ###


def downgrade():
	# ### commands auto generated by Alembic - please adjust! ###
	with op.batch_alter_table('recipe', schema=None) as batch_op:
		batch_op.drop_column('image')
		try:
			pass
		# batch_op.drop_column('number')
		except KeyError:
			pass

# ### end Alembic commands ###
