"""empty message

Revision ID: a6a95ac4141a
Revises: 850981e700c2
Create Date: 2026-03-07 20:44:55.173193

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'a6a95ac4141a'
down_revision = '850981e700c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe_ingredient',
                    sa.Column('ingredient_list', sa.String(length=100), nullable=False),
                    sa.Column('amount', sa.Float(), nullable=True),
                    sa.Column('unit', sa.String(length=20), nullable=True),
                    sa.Column('recipe_slug', sa.String(length=100), nullable=False),
                    sa.Column('ingredient_slug', sa.String(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_slug'], ['ingredient.slug'], ),
                    sa.ForeignKeyConstraint(['recipe_slug'], ['recipe.slug'], ),
                    sa.PrimaryKeyConstraint('ingredient_list', 'recipe_slug', 'ingredient_slug')
                    )
    op.drop_table('recipe_ingredient_schema')
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cook_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('prep_time', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cook_temp', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('servings', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recipe', schema=None) as batch_op:
        batch_op.drop_column('servings')
        batch_op.drop_column('cook_temp')
        batch_op.drop_column('prep_time')
        batch_op.drop_column('cook_time')

    op.create_table('recipe_ingredient_schema',
                    sa.Column('ingredient_list', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('amount', sa.FLOAT(), nullable=True),
                    sa.Column('unit', sa.VARCHAR(length=20), nullable=True),
                    sa.Column('recipe_slug', sa.VARCHAR(length=100), nullable=False),
                    sa.Column('ingredient_slug', sa.VARCHAR(length=50), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_slug'], ['ingredient.slug'], ),
                    sa.ForeignKeyConstraint(['recipe_slug'], ['recipe.slug'], ),
                    sa.PrimaryKeyConstraint('ingredient_list', 'recipe_slug', 'ingredient_slug')
                    )
    op.drop_table('recipe_ingredient')
    # ### end Alembic commands ###
