"""Tag system

Revision ID: c7ec534265ff
Revises: 03ffea81ea23
Create Date: 2026-04-14 09:43:54.770349

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'c7ec534265ff'
down_revision = '03ffea81ea23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tag',
                    sa.Column('name', sa.String(length=100), nullable=False, case_sensitive=False),
                    sa.PrimaryKeyConstraint('name'),
                    sa.UniqueConstraint('name')
                    )
    op.create_table('ingredient_tag',
                    sa.Column('ingredient_slug', sa.String(length=50), nullable=False),
                    sa.Column('tag_name', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['ingredient_slug'], ['ingredient.slug'], ),
                    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
                    sa.PrimaryKeyConstraint('ingredient_slug', 'tag_name')
                    )
    op.create_table('recipe_tag',
                    sa.Column('recipe_slug', sa.String(length=100), nullable=False),
                    sa.Column('tag_name', sa.String(length=100), nullable=False),
                    sa.ForeignKeyConstraint(['recipe_slug'], ['recipe.slug'], ),
                    sa.ForeignKeyConstraint(['tag_name'], ['tag.name'], ),
                    sa.PrimaryKeyConstraint('recipe_slug', 'tag_name')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recipe_tag')
    op.drop_table('ingredient_tag')
    op.drop_table('tag')
    # ### end Alembic commands ###
